### ISSUE TITLE
[Bug]: Widget queries does not handle multi-property filters

### ISSUE THREAD

**Issue by taorepoara** [lenra-io/Lenra#180] opened 2022-10-24 14:40 UTC
### What happened?

I use a query with two properties filtering the documents. This widget is built the first time (using the MongoDB database), but fails when it's rebuilt with a document change (the data property is an empty array).

Here is the source code: https://github.com/lenra-io/app-minella/blob/a41b67f68174201b68a81ec3acf8748e03943907/widgets/components/gameList.js#L90

### Version

devtool: v1.0.0-beta.67

**Comment by taorepoara** [comment] 2022-10-26 14:05
On Minella this error occurs when creating a multiplayer game (with both players).

**Comment by pichoemr** [comment] 2022-11-07 13:55
@lenra-io/devs 
After a few tests, the problem is when the query server is started, the initialization data returns an empty value.

when the user interface changes, we initiate a new widget server for the new widget, in this case a widget_card, during the init we call QueryServer.get_data to get the data (line 41).
the dinamyc widget supervisor makes sure that the request server is started, in our case we don't have a request server yet so we start a new one.
The problem occurs at this time, during the initialization of the request server, here are the logs:

```
{:query, :init,
//query
 %{
   "game" => "ObjectId(635a9e781d41c8b30df270cd)",
   "user" => "562a4293-b690-4d78-9bd6-ee1aa4e8645e"
 },
 //initial data
 []
}
```
we have the right query but the initial data requested from Mongo is empty, knowing that the user interface only changes when the Mongo collection changes, we have data in Mongo.
Need more tests to find the problem, any ideas are welcome...

**Comment by Nesqwik** [comment] 2022-11-10 13:05
I think i understand the issue.
The query 
```
%{
   "game" => "ObjectId(635a9e781d41c8b30df270cd)",
   "user" => "562a4293-b690-4d78-9bd6-ee1aa4e8645e"
 }
 ```
 contains an ObjectID that need to be parsed before running the query to mongo.
 To do this, simply transform the query using `MongoStorage.decode_ids/1`.

**Comment by pichoemr** [comment] 2022-11-14 13:43
@Nesqwik in fact we already filter the Object_id, the logs were done before filtering but the query use MongoStorage.filter_docs which decodes the ids.

**Comment by pichoemr** [comment] 2022-11-21 13:48
After some discussion, the problem seems to be wanted, the widget crash so we cannot update it later.
We can make the interface reload only when the listeners finished, but we may have problems with long listeners.
We probably want to implement the mongo transaction

I close this issue and the work will be done here https://github.com/lenra-io/application-runner/issues/200

**Closed by pichoemr** 2022-11-21 13:48 UTC
Labels: bug
